apiVersion: v1
kind: Service
metadata:
  name: bookmyshow-service
  labels:
    app: bookmyshow
spec:
  type: NodePort
  selector:
    app: bookmyshow
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
